window.MAP_CONFIG = {
    "allTables": {
        "1": [
            {
                "id": "1",
                "table_number": "VVIP1",
                "table_type": "VVIP",
                "capacity": 4,
                "x_position": 22,
                "y_position": 15,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#8f195e"
            },
            {
                "id": "2",
                "table_number": "VVIP2",
                "table_type": "VVIP",
                "capacity": 4,
                "x_position": 21,
                "y_position": 29,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#8f195e"
            },
            {
                "id": "3",
                "table_number": "VVIP3",
                "table_type": "VVIP",
                "capacity": 4,
                "x_position": 28,
                "y_position": 29,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#8f195e"
            },
            {
                "id": "4",
                "table_number": "VVIP4",
                "table_type": "VVIP",
                "capacity": 4,
                "x_position": 35,
                "y_position": 29,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#8f195e"
            },
            {
                "id": "5",
                "table_number": "VVIP5",
                "table_type": "VVIP",
                "capacity": 4,
                "x_position": 42,
                "y_position": 29,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#8f195e"
            },
            {
                "id": "6",
                "table_number": "VVIP6",
                "table_type": "VVIP",
                "capacity": 4,
                "x_position": 49,
                "y_position": 15,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#8f195e"
            },
            {
                "id": "7",
                "table_number": "VIP8",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 15,
                "y_position": 30,
                "span_x": 6,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#e84946"
            },
            {
                "id": "8",
                "table_number": "VIP9",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 23,
                "y_position": 50,
                "span_x": 6,
                "span_y": 13,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#e84946"
            },
            {
                "id": "9",
                "table_number": "VIP10",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 35,
                "y_position": 69,
                "span_x": 8,
                "span_y": 10,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#e84946"
            },
            {
                "id": "10",
                "table_number": "VIP11",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 45,
                "y_position": 69,
                "span_x": 8,
                "span_y": 10,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#e84946"
            },
            {
                "id": "11",
                "table_number": "VIP12",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 55,
                "y_position": 69,
                "span_x": 8,
                "span_y": 10,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#e84946"
            },
            {
                "id": "12",
                "table_number": "T13",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 8,
                "y_position": 17,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "13",
                "table_number": "T14",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 8,
                "y_position": 30,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "14",
                "table_number": "T15",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 8,
                "y_position": 41,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "15",
                "table_number": "T16",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 8,
                "y_position": 51,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "16",
                "table_number": "T17",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 57,
                "y_position": 14,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "17",
                "table_number": "T18",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 57,
                "y_position": 28,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "18",
                "table_number": "T19",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 50,
                "y_position": 31,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "19",
                "table_number": "T20",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 25,
                "y_position": 41,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "20",
                "table_number": "T21",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 32,
                "y_position": 41,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "21",
                "table_number": "T22",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 41,
                "y_position": 41,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "22",
                "table_number": "T23",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 49,
                "y_position": 41,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "23",
                "table_number": "T24",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 32,
                "y_position": 49,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "24",
                "table_number": "T25",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 41,
                "y_position": 49,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "25",
                "table_number": "T27",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 32,
                "y_position": 58,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "26",
                "table_number": "T28",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 41,
                "y_position": 58,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "27",
                "table_number": "T29",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 49,
                "y_position": 58,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "28",
                "table_number": "T30",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 57,
                "y_position": 41,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "29",
                "table_number": "T31",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 57,
                "y_position": 49,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "30",
                "table_number": "T32",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 57,
                "y_position": 58,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "31",
                "table_number": "S33",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 67,
                "y_position": 18,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "32",
                "table_number": "S34",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 73,
                "y_position": 18,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "33",
                "table_number": "S35",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 78,
                "y_position": 18,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "34",
                "table_number": "S36",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 84,
                "y_position": 18,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "35",
                "table_number": "S37",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 89,
                "y_position": 18,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "36",
                "table_number": "S38",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 67,
                "y_position": 27,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "37",
                "table_number": "S39",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 73,
                "y_position": 27,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "38",
                "table_number": "S40",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 78,
                "y_position": 27,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "39",
                "table_number": "S41",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 84,
                "y_position": 27,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "40",
                "table_number": "S42",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 89,
                "y_position": 27,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "41",
                "table_number": "S43",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 67,
                "y_position": 59,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "42",
                "table_number": "S44",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 73,
                "y_position": 59,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "43",
                "table_number": "S45",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 78,
                "y_position": 59,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "44",
                "table_number": "S46",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 84,
                "y_position": 59,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "45",
                "table_number": "S47",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 89,
                "y_position": 59,
                "span_x": 5,
                "span_y": 7,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "46",
                "table_number": "S48",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 67,
                "y_position": 68,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "47",
                "table_number": "S49",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 75,
                "y_position": 68,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "48",
                "table_number": "S50",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 83,
                "y_position": 68,
                "span_x": 7,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "49",
                "table_number": "S51",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 90,
                "y_position": 68,
                "span_x": 5,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#714628"
            },
            {
                "id": "50",
                "table_number": "T26",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 49,
                "y_position": 49,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#008927"
            },
            {
                "id": "51",
                "table_number": "VIP7",
                "table_type": "Normal",
                "capacity": 4,
                "x_position": 15,
                "y_position": 17,
                "span_x": 6,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#e84946"
            }
        ],
        "2": []
    },
    "concertDetails": {
        "extra_chair_price": 200,
        "lock_table_price": 500,
        "ticket_price_vvip_2": 0,
        "ticket_price_vvip_4": 4000,
        "ticket_price_vvip_6": 6000,
        "ticket_price_vip_2": 0,
        "ticket_price_vip_4": 3000,
        "ticket_price_vip_6": 4500,
        "ticket_price_normal_2": 0,
        "ticket_price_normal_4": 2000,
        "ticket_price_normal_6": 3000,
        "ticket_price_small_2": 1000,
        "ticket_price_small_4": 0,
        "ticket_price_small_6": 0,
        "privilege_vvip": "โซฟาติดขอบเวที",
        "privilege_vip": "มองเห็นชัดเจน",
        "privilege_normal": "โต๊ะนั่งสบาย",
        "privilege_small": "โต๊ะยืนชิลๆ"
    },
    "structCSS": ".station-2 { grid-column: 7 / span 15; grid-row: 62 / span 15; }\n.station-4 { grid-column: 69 / span 19; grid-row: 41 / span 10; }\n.station-6 { grid-column: 33 / span 12; grid-row: 14 / span 14; }\n.station-7 { grid-column: 23 / span 10; grid-row: 71 / span 9; }\n",
    "structHTML": "<div id=\"restaurant-layout\" class=\"animate-fade\">\n    <div class=\"station-2\">บาร์น้ำ</div>\n    <div class=\"station-4\">ทางเข้า</div>\n    <div class=\"station-6\">เวที</div>\n    <div class=\"station-7\">DJ</div>\n</div>"
};