name = "craftopiacore"
main = "worker.js"
compatibility_date = "2023-10-30"

[[d1_databases]]
binding = "DB"
database_name = "concert-db"
database_id = "7498d13b-3ea7-457e-a063-055f510b2ac5"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "concert-bucket"
