window.MAP_CONFIG = {
    "allTables": {
        "1": [
            {
                "id": "65",
                "table_number": "F1",
                "table_type": "square",
                "capacity": 4,
                "x_position": 16,
                "y_position": 12,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#fbbf24",
                "price": "2500",
                "extra_price": "200"
            },
            {
                "id": "66",
                "table_number": "F2",
                "table_type": "square",
                "capacity": 4,
                "x_position": 27,
                "y_position": 12,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#fbbf24",
                "price": "2500",
                "extra_price": "200"
            },
            {
                "id": "67",
                "table_number": "F3",
                "table_type": "square",
                "capacity": 4,
                "x_position": 40,
                "y_position": 12,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#fbbf24",
                "price": "2500",
                "extra_price": "200"
            },
            {
                "id": "68",
                "table_number": "F4",
                "table_type": "square",
                "capacity": 4,
                "x_position": 51,
                "y_position": 12,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#fbbf24",
                "price": "2500",
                "extra_price": "200"
            },
            {
                "id": "69",
                "table_number": "F5",
                "table_type": "square",
                "capacity": 4,
                "x_position": 63,
                "y_position": 12,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#fbbf24",
                "price": "2500",
                "extra_price": "200"
            },
            {
                "id": "70",
                "table_number": "F6",
                "table_type": "square",
                "capacity": 4,
                "x_position": 75,
                "y_position": 12,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#fbbf24",
                "price": "2500",
                "extra_price": "200"
            },
            {
                "id": "72",
                "table_number": "F7",
                "table_type": "square",
                "capacity": 4,
                "x_position": 10,
                "y_position": 19,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "73",
                "table_number": "F8",
                "table_type": "square",
                "capacity": 4,
                "x_position": 22,
                "y_position": 19,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "74",
                "table_number": "F9",
                "table_type": "square",
                "capacity": 4,
                "x_position": 33,
                "y_position": 19,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "75",
                "table_number": "F10",
                "table_type": "square",
                "capacity": 4,
                "x_position": 45,
                "y_position": 19,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "76",
                "table_number": "F11",
                "table_type": "square",
                "capacity": 4,
                "x_position": 57,
                "y_position": 19,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "77",
                "table_number": "F12",
                "table_type": "square",
                "capacity": 4,
                "x_position": 69,
                "y_position": 19,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "78",
                "table_number": "F13",
                "table_type": "square",
                "capacity": 4,
                "x_position": 81,
                "y_position": 19,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "79",
                "table_number": "F14",
                "table_type": "square",
                "capacity": 4,
                "x_position": 10,
                "y_position": 27,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "80",
                "table_number": "F15",
                "table_type": "square",
                "capacity": 4,
                "x_position": 21,
                "y_position": 27,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "81",
                "table_number": "F16",
                "table_type": "square",
                "capacity": 4,
                "x_position": 33,
                "y_position": 27,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "83",
                "table_number": "F17",
                "table_type": "square",
                "capacity": 4,
                "x_position": 46,
                "y_position": 27,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "84",
                "table_number": "F18",
                "table_type": "square",
                "capacity": 4,
                "x_position": 57,
                "y_position": 27,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "85",
                "table_number": "F19",
                "table_type": "square",
                "capacity": 4,
                "x_position": 69,
                "y_position": 27,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "86",
                "table_number": "F20",
                "table_type": "square",
                "capacity": 4,
                "x_position": 80,
                "y_position": 27,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#476fff",
                "price": "2000",
                "extra_price": "200"
            },
            {
                "id": "87",
                "table_number": "V1",
                "table_type": "round",
                "capacity": 4,
                "x_position": 54,
                "y_position": 94,
                "span_x": 6,
                "span_y": 5,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "88",
                "table_number": "V2",
                "table_type": "round",
                "capacity": 4,
                "x_position": 57,
                "y_position": 89,
                "span_x": 6,
                "span_y": 5,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "89",
                "table_number": "V3",
                "table_type": "round",
                "capacity": 4,
                "x_position": 61,
                "y_position": 84,
                "span_x": 6,
                "span_y": 5,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "93",
                "table_number": "V4",
                "table_type": "round",
                "capacity": 4,
                "x_position": 65,
                "y_position": 80,
                "span_x": 6,
                "span_y": 5,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "94",
                "table_number": "V5",
                "table_type": "round",
                "capacity": 4,
                "x_position": 69,
                "y_position": 75,
                "span_x": 6,
                "span_y": 5,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "95",
                "table_number": "V6",
                "table_type": "round",
                "capacity": 4,
                "x_position": 72,
                "y_position": 71,
                "span_x": 6,
                "span_y": 5,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "96",
                "table_number": "V7",
                "table_type": "round",
                "capacity": 4,
                "x_position": 74,
                "y_position": 65,
                "span_x": 6,
                "span_y": 5,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "97",
                "table_number": "V8",
                "table_type": "round",
                "capacity": 4,
                "x_position": 74,
                "y_position": 60,
                "span_x": 6,
                "span_y": 5,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "98",
                "table_number": "V9",
                "table_type": "round",
                "capacity": 4,
                "x_position": 74,
                "y_position": 54,
                "span_x": 6,
                "span_y": 5,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "99",
                "table_number": "V10",
                "table_type": "round",
                "capacity": 4,
                "x_position": 74,
                "y_position": 49,
                "span_x": 6,
                "span_y": 5,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "100",
                "table_number": "V11",
                "table_type": "round",
                "capacity": 4,
                "x_position": 74,
                "y_position": 44,
                "span_x": 6,
                "span_y": 5,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "101",
                "table_number": "V12",
                "table_type": "round",
                "capacity": 4,
                "x_position": 74,
                "y_position": 39,
                "span_x": 6,
                "span_y": 5,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "103",
                "table_number": "V13",
                "table_type": "round",
                "capacity": 4,
                "x_position": 39,
                "y_position": 89,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "104",
                "table_number": "V14",
                "table_type": "round",
                "capacity": 4,
                "x_position": 26,
                "y_position": 89,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "105",
                "table_number": "V15",
                "table_type": "round",
                "capacity": 4,
                "x_position": 51,
                "y_position": 78,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "106",
                "table_number": "V16",
                "table_type": "round",
                "capacity": 4,
                "x_position": 40,
                "y_position": 78,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "107",
                "table_number": "V17",
                "table_type": "round",
                "capacity": 4,
                "x_position": 56,
                "y_position": 67,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "108",
                "table_number": "V18",
                "table_type": "round",
                "capacity": 4,
                "x_position": 41,
                "y_position": 67,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "109",
                "table_number": "V19",
                "table_type": "round",
                "capacity": 4,
                "x_position": 66,
                "y_position": 59,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "110",
                "table_number": "V20",
                "table_type": "round",
                "capacity": 4,
                "x_position": 59,
                "y_position": 59,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "111",
                "table_number": "V21",
                "table_type": "round",
                "capacity": 4,
                "x_position": 66,
                "y_position": 51,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "112",
                "table_number": "V22",
                "table_type": "round",
                "capacity": 4,
                "x_position": 59,
                "y_position": 52,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "113",
                "table_number": "V23",
                "table_type": "round",
                "capacity": 4,
                "x_position": 27,
                "y_position": 77,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "114",
                "table_number": "V24",
                "table_type": "round",
                "capacity": 4,
                "x_position": 27,
                "y_position": 66,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "115",
                "table_number": "V25",
                "table_type": "round",
                "capacity": 4,
                "x_position": 40,
                "y_position": 58,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "116",
                "table_number": "V26",
                "table_type": "round",
                "capacity": 4,
                "x_position": 48,
                "y_position": 49,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "117",
                "table_number": "V27",
                "table_type": "round",
                "capacity": 4,
                "x_position": 58,
                "y_position": 44,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "118",
                "table_number": "V28",
                "table_type": "round",
                "capacity": 4,
                "x_position": 64,
                "y_position": 37,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            },
            {
                "id": "119",
                "table_number": "V29",
                "table_type": "round",
                "capacity": 4,
                "x_position": 25,
                "y_position": 55,
                "span_x": 7,
                "span_y": 6,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#b51a00",
                "price": "0",
                "extra_price": "0"
            }
        ],
        "2": []
    },
    "concertDetails": {
        "allow_lock_table": false,
        "extra_chair_price": 200,
        "lock_table_price": 500,
        "colorPrices": {},
        "privilege_vvip": "โซฟาติดขอบเวที",
        "privilege_vip": "มองเห็นชัดเจน",
        "privilege_normal": "โต๊ะนั่งสบาย",
        "privilege_small": "โต๊ะยืนชิลๆ"
    },
    "structCSS": ".station-5 { grid-column: 10 / span 12; grid-row: 67 / span 27; }\n.station-6 { grid-column: 49 / span 9; grid-row: 56 / span 7; }\n.station-7 { grid-column: 82 / span 9; grid-row: 37 / span 36; }\n.station-8 { grid-column: 57 / span 38; grid-row: 83 / span 7; transform: rotate(-59.77460802048872deg); }\n",
    "structHTML": "<div id=\"restaurant-layout\" class=\"animate-fade\">\n    <div class=\"station-5\">เวที</div>\n    <div class=\"station-6\">x</div>\n    <div class=\"station-7\">โซฟา</div>\n    <div class=\"station-8\">โซฟา</div>\n</div>"
};