window.MAP_CONFIG = {
    "allTables": {
        "1": [
            {
                "id": "1",
                "table_number": "7",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 1,
                "y_position": 45,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "2",
                "table_number": "8",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 1,
                "y_position": 54,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "3",
                "table_number": "9",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 1,
                "y_position": 64,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "4",
                "table_number": "10",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 1,
                "y_position": 72,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "5",
                "table_number": "11",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 1,
                "y_position": 81,
                "span_x": 11,
                "span_y": 9,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "6",
                "table_number": "12",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 1,
                "y_position": 91,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "7",
                "table_number": "1",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 33,
                "y_position": 1,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "8",
                "table_number": "2",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 27,
                "y_position": 7,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "9",
                "table_number": "3",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 21,
                "y_position": 15,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "10",
                "table_number": "4",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 15,
                "y_position": 22,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "11",
                "table_number": "5",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 9,
                "y_position": 29,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "12",
                "table_number": "6",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 4,
                "y_position": 37,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "13",
                "table_number": "19",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 15,
                "y_position": 56,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "14",
                "table_number": "20",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 25,
                "y_position": 56,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "15",
                "table_number": "21",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 14,
                "y_position": 67,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "16",
                "table_number": "22",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 25,
                "y_position": 67,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "17",
                "table_number": "13",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 49,
                "y_position": 8,
                "span_x": 11,
                "span_y": 9,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "18",
                "table_number": "15",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 35,
                "y_position": 24,
                "span_x": 11,
                "span_y": 9,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "19",
                "table_number": "16",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 49,
                "y_position": 25,
                "span_x": 11,
                "span_y": 9,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "20",
                "table_number": "17",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 25,
                "y_position": 38,
                "span_x": 11,
                "span_y": 9,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "21",
                "table_number": "18",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 47,
                "y_position": 41,
                "span_x": 11,
                "span_y": 9,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "22",
                "table_number": "25",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 47,
                "y_position": 57,
                "span_x": 11,
                "span_y": 9,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "23",
                "table_number": "26",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 42,
                "y_position": 71,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "24",
                "table_number": "14",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 68,
                "y_position": 8,
                "span_x": 11,
                "span_y": 9,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "25",
                "table_number": "23",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 62,
                "y_position": 25,
                "span_x": 11,
                "span_y": 9,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "26",
                "table_number": "24",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 62,
                "y_position": 42,
                "span_x": 11,
                "span_y": 9,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "27",
                "table_number": "29",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 62,
                "y_position": 58,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "28",
                "table_number": "27",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 25,
                "y_position": 78,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            },
            {
                "id": "29",
                "table_number": "28",
                "table_type": "VIP",
                "capacity": 4,
                "x_position": 16,
                "y_position": 89,
                "span_x": 10,
                "span_y": 8,
                "is_available": true,
                "allow_extra_chairs": true,
                "max_extra_chairs": 2,
                "custom_color": "#ffffff",
                "price": ""
            }
        ],
        "2": []
    },
    "concertDetails": {
        "extra_chair_price": 200,
        "lock_table_price": 500,
        "colorPrices": {
            "#ffffff": 0
        },
        "privilege_vvip": "โซฟาติดขอบเวที",
        "privilege_vip": "มองเห็นชัดเจน",
        "privilege_normal": "โต๊ะนั่งสบาย",
        "privilege_small": "โต๊ะยืนชิลๆ"
    },
    "structCSS": ".station-1 { grid-column: 54 / span 27; grid-row: 87 / span 11; }\n.station-2 { grid-column: 85 / span 13; grid-row: 21 / span 30; }\n.station-3 { grid-column: 33 / span 46; grid-row: 1 / span 9; }\n.station-4 { grid-column: 54 / span 23; grid-row: 1 / span 7; }\n.station-5 { grid-column: 8 / span 10; grid-row: 1 / span 44; transform: rotate(35deg); }\n.station-6 { grid-column: 1 / span 73; grid-row: 66 / span 7; transform: rotate(90deg); }\n",
    "structHTML": "<div id=\"restaurant-layout\" class=\"animate-fade\">\n    <div class=\"station-1\">ทางเข้า</div>\n    <div class=\"station-2\">เวที</div>\n    <div class=\"station-3\">บาร์</div>\n    <div class=\"station-4\">ห้องน้ำ</div>\n    <div class=\"station-5\">โซฟา</div>\n    <div class=\"station-6\">โซฟา</div>\n</div>"
};