name = "bart-time-check"
main = "src/index.js"
compatibility_date = "2024-02-16"

[[d1_databases]]
binding = "DB"
database_name = "REPLACE_WITH_YOUR_DB_NAME"
database_id = "REPLACE_WITH_YOUR_DB_ID"

[ai]
binding = "AI"
